name: Bug Report
description: File a bug report.
labels: ["bug"]
projects: ["usu-accessibility/6"]
body:
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please explain in detail what the expected behavior is.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Please explain in detail what the actual behavior is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce the Problem
      description: Please explain what steps you took to run into this issue.
      value: |
        1. 
        2. 
        3.
        ...
    validations:
      required: true
  - type: dropdown
    id: issue-product
    attributes:
      label: In Which Product Was the Problem Seen
      options:
        - Monday.com
        - Standalone Application
        - Other
      default: 0
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Issue Page
      description: A url of the page with problem.
    validations:
      required: false
